version: '3'

services:

  api:
    build: .
    ports:
      - "8080:8080"
    environment:
      - DB_URL=jdbc:postgresql://db:5432/jvs
      - DB_USER=jvs
      - DB_PASSWORD=jvs
    depends_on:
      - db

  db:
    image: postgres:11-alpine
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=jvs
      - POSTGRES_PASSWORD=jvs
    volumes:
      - ./setup/db:/docker-entrypoint-initdb.d/



